### ISSUE TITLE
Allow use to set output size of hash, and set the default to the same as in spec

### ISSUE THREAD

**Issue by Rudde** [azureskydiver/Blake3Core#1]
Should probably have the option to allow the user to set the desired output length of the BLAKE3 hash as the default values across libs and systems is already not always the same. This also have the default output size of 512 bites which is conflicting with the BLAKE3 spec stating it should be 256 bits. 

Would also be cool to have som comparison with other C# BLAKE3 like Blake3.NET, which I do understand it might not beat in pure performance considering how different these are. But it would still be cool to see the a comparison. And which natively implemented hashing algorithms in C# like Sha256 as BLAKE3 is known to beat.

**Comment by azureskydiver** [comment]
Good catch. I assumed that `HashAlgorithm.HashSize` was a get/set property, and that users could just set their desired size. Apparently it's a get only property. Let me noodle on this a bit whether to declare a new `Blake3.HashSize` that is get/set or just pass this in as a constructor parameter. (I'm kind of leaning towards the latter.)

I also missed the 256 bit size thing. I was so focused on looking at the reference source, and it didn't seem to do anything to limit things to just 256 bits. In fact, the various tests for the reference source was trying to go way beyond the default block sizes.

Since the code is based on the reference source, it doesn't have any of the cool low level vector optimizations that the various native implementations has. The built-in .NET SHA implementations have various optimizations as I recall. I was originally going to try to tackle some multi-threaded optimizations to try to speed things up, but I got side tracked with real work.

Pull requests and forks are more than welcome. (Hint. Hint.)
